In [26]:
import pandas as pd

In [27]:
df_materias_xslx = pd.read_excel('../data/riesgo_academico/saved/TODOESPOL.xlsx')

In [28]:
df_materias_xslx["CodigoMateria"].nunique()

726

In [29]:
# df_materias = pd.read_csv("../data/riesgo_academico/dificultad_materia.csv")

In [30]:
# df_materias["CODIGOMATERIA"].nunique()

In [31]:
# df_materias["CODIGOMATERIA"].value_counts()

In [32]:
df_new_semester = pd.read_csv("../data/riesgo_academico/all_2026_1S.csv")

In [33]:
df_new_semester["COD_MATERIA_ACAD_MO"].nunique()

640

In [34]:
df_new_semester["MATERIA"].unique()

array(['SISTEMAS ACUÍCOLAS', 'PRODUCCIÓN ACUÍCOLA II',
       'CULTIVO DE PLANCTON', 'ANÁLISIS DE DATOS ACUÍCOLAS',
       'QUÍMICA GENERAL', 'INGLÉS III', 'INTRODUCCIÓN A LA ACUICULTURA',
       'CULTIVO DE ESPECIES NO TRADICIONALES', 'PISCICULTURA',
       'PRODUCCIÓN ACUICOLA I', 'CIENCIAS DE LA SOSTENIBILIDAD',
       'ACUICULTURA ORNAMENTAL', 'BUENAS PRÁCTICAS EN ACUICULTURA',
       'INGLÉS II', 'NUTRICIÓN ACUÍCOLA', 'INGLÉS V',
       'MORFOLOGÍA Y FISIOLOGÍA DE ORGANISMOS ACUÍCOLAS',
       'FUNDAMENTOS DE INGENIERÍA ACUÍCOLA',
       'HERRAMIENTAS PARA EL DIAGNÓSTICO DE ENFERMEDADES ACUÍCOLAS',
       'EMPRENDIMIENTO E INNOVACIÓN',
       'PROBLEMAS DE LA ACTUALIDAD ACUÍCOLA', 'BIOQUÍMICA',
       'BIOLOGÍA GENERAL', 'COMUNICACIÓN', 'CÁLCULO DE UNA VARIABLE',
       'INGLÉS IV', 'ANÁLISIS Y RESOLUCIÓN DE PROBLEMAS',
       'ECOSISTEMAS ACUÍCOLAS', 'PATOLOGÍA ACUÍCOLA II',
       'PATOLOGÍA ACUÍCOLA I', 'INGENIERÍA PARA LA ACUICULTURA II',
       'MANEJO ACUÍCOLA', 'INGENIERÍA PARA LA ACUICULTURA I',
       'ESTADÍSTICA', 'FUNDAMENTOS DE PROGRAMACIÓN',
       'CÁLCULO DE VARIAS VARIABLES', 'QUÍMICA ORGÁNICA', 'INGLÉS I',
       'EVOLUCIÓN', 'BIOINFORMÁTICA',
       'INVESTIGACIÓN EN CIENCIAS DE LA VIDA', 'EMBRIOLOGÍA',
       'ECOLOGÍA DE ECOSISTEMAS', 'PRINCIPIOS DE ECOTOXICOLOGÍA',
       'INMUNOLOGÍA', 'ECOLOGÍA ACUÁTICA', 'REMEDIACIÓN AMBIENTAL',
       'FISIOLOGÍA VEGETAL', 'BOTÁNICA SISTEMÁTICA', 'BIOESTADÍSTICA',
       'VIROLOGÍA', 'ZOOLOGÍA DE VERTEBRADOS', 'ENTOMOLOGÍA',
       'ZOOLOGÍA DE INVERTEBRADOS', 'ECOLOGÍA GENERAL',
       'FISIOLOGÍA ANIMAL', 'BIOLOGÍA CELULAR Y MOLECULAR',
       'MICROBIOLOGÍA GENERAL', 'BIOGEOGRAFÍA',
       'INTRODUCCIÓN A LAS HERRAMIENTAS ÓMICAS',
       'CONTAMINACIÓN AMBIENTAL', 'OPERACIONES UNITARIAS I',
       'FÍSICA: MECÁNICA', 'DISEÑO DE PLANTAS', 'CINÉTICA Y REACTORES',
       'DINÁMICA DE PROCESOS Y CONTROL', 'FISICOQUÍMICA',
       'TRATAMIENTO DE AGUAS', 'FÍSICA: ELECTRÓNICA Y ÓPTICA',
       'TERMODINÁMICA I', 'QUÍMICA ORGÁNICA II',
       'MATEMÁTICA APLICADA A LA INGENIERÍA',
       'BALANCE DE MATERIA Y ENERGÍA', 'QUÍMICA INORGÁNICA',
       'QUÍMICA ORGÁNICA I',
       'GESTIÓN DE CALIDAD, AMBIENTE Y SEGURIDAD EN LA INDUSTRIA',
       'OPTIMIZACIÓN Y SIMULACIÓN DE PROCESOS ALIMENTARIOS',
       'SISTEMAS DE INFORMACIÓN', 'FÍSICA: ELECTRICIDAD Y MAGNETISMO',
       'FENÓMENOS DE TRANSPORTE DE MOMENTUM',
       'QUÍMICA ANALÍTICA E INSTRUMENTAL',
       'ECUACIONES DIFERENCIALES Y ÁLGEBRA LINEAL', 'CÁLCULO VECTORIAL',
       'MÉTODOS NUMÉRICOS', 'DISEÑO DE SISTEMAS TERMOFLUIDOS',
       'PLANIFICACIÓN DE SISTEMAS DE POTENCIA',
       'FORMULACION Y EVALUACIÓN SOCIAL DE PROYECTOS',
       'SISTEMAS DE CONTROL APLICADOS', 'INTERACCIÓN HUMANO COMPUTADOR',
       'DIETOTERAPIA AVANZADA', 'DIBUJO  I', 'DISEÑO MECÁNICO',
       'AGENCIAS DE VIAJE', 'DISEÑO ESTRATÉGICO', 'SISTEMAS EMBEBIDOS',
       'ROBÓTICA INDUSTRIAL', 'CONTABILIDAD AVANZADA',
       'ESTRATEGIAS CORPORATIVAS Y DE NEGOCIOS',
       'ELECTRÓNICA DE POTENCIA I',
       'INTRODUCCIÓN AL RAZONAMIENTO MATEMÁTICO',
       'ESTRATEGIAS DE GESTIÓN', 'INVESTIGACIÓN DE OPERACIONES',
       'ARTE Y CIENCIA', 'EDICIÓN Y MONTAJE', 'SISTEMAS OPERATIVOS',
       'CONTROL DE CALIDAD Y EVALUACIÓN SENSORIAL DE ALIMENTOS',
       'SISTEMAS DISTRIBUIDOS Y COMPUTACIÓN EN LA NUBE',
       'ELEMENTOS FINITOS', 'INGENIERÍA DE SOFTWARE II',
       'ARTE Y TECNOLOGÍA', 'SEMIÓTICA',
       'CALIDAD DE SERVICIO Y REDES MULTIMEDIA',
       'CONSTRUCCIONES METÁLICAS DE BUQUES', 'INSTALACIONES ELÉCTRICAS',
       'DERECHO TURÍSTICO Y AMBIENTAL', 'DISEÑO GRÁFICO IV',
       'DIBUJO PARA INGENIERÍA', 'FUNDAMENTOS DE ADMINISTRACIÓN',
       'MACROECONOMÍA I', 'PROYECTO AUDIOVISUAL I', 'HISTORIA DEL ARTE',
       'NUTRICIÓN VEGETAL', 'INTRODUCCIÓN A LA INGENIERÍA MECÁNICA',
       'METAHEURÍSTICAS', 'CONTABILIDAD FINANCIERA',
       'MANTENIMIENTO INDUSTRIAL',
       'AMBIENTE Y GESTIÓN DE RESIDUOS MINEROS',
       'SIMULACIÓN DE RESERVORIOS', 'GESTIÓN TRIBUTARIA',
       'INTRODUCCIÓN A LA ECONOMÍA', 'MARKETING TURÍSTICO',
       'POSTPRODUCCIÓN', 'DIRECCIÓN DE ARTE', 'FOTOGRAFÍA DIGITAL',
       'PLANIFICACIÓN ESTRATÉGICA', 'TELEMETRÍA Y SISTEMAS CIBERFÍSICOS',
       'POTABILIZACIÓN Y TRATAMIENTO DEL AGUA', 'VIBRACIONES MECÁNICAS',
       'INTRODUCCIÓN A LAS TELECOMUNICACIONES',
       'COMUNICACIONES INALÁMBRICAS', 'ESTADÍSTICA I',
       'GESTIÓN DE BODEGAS Y ABASTECIMIENTO', 'DISEÑO DE INFORMACIÓN',
       'PLANIFICACIÓN DE LA PRODUCCIÓN', 'INTELIGENCIA ARTIFICIAL',
       'ANÁLISIS FINANCIERO', 'INGENIERÍA DE MÉTODOS', 'HORMIGÓN ARMADO',
       'SIMULACIÓN MATEMÁTICA', 'DISEÑO DE PLANTAS ALIMENTARIAS',
       'PRODUCCIÓN EJECUTIVA', 'FUNDAMENTOS DE INVERSIONES',
       'TRANSMISIÓN DE SERVICIOS MULTIMEDIA', 'ECONOMETRÍA III',
       'DISEÑO DE REDES CONMUTADAS', 'ELECTRICIDAD BÁSICA',
       'ESTADÍSTICA II', 'ESTABILIDAD DEL BUQUE',
       'PROYECTOS INDUSTRIALES', 'OPTIMIZACIÓN NUMÉRICA',
       'DISEÑO DE APLICACIONES EN TELECOMUNICACIONES',
       'AUDITORÍA OPERACIONAL', 'OPERACIÓN TURÍSTICA', 'CONTABILIDAD II',
       'SISTEMAS DE INFORMACIÓN GEOGRÁFICA', 'GESTIÓN DE PROYECTOS',
       'PROYECTO DE DISEÑO', 'FORMULACIÓN Y EVALUACIÓN DE PROYECTOS',
       'DIRECCIÓN AUDIOVISUAL', 'ENERGÍAS RENOVABLES', 'GESTIÓN HOTELERA',
       'DISEÑO EDITORIAL', 'COMUNICACIÓN DIGITAL DE DATOS',
       'DISEÑO DE PUENTES', 'PRESUPUESTOS Y PROYECTOS LOGÍSTICOS',
       'CIBERSEGURIDAD Y GESTIÓN DE REDES', 'REDACCIÓN CREATIVA',
       'ECONOMETRÍA I', 'MODELOS ESTADÍSTICOS APLICADOS II',
       'CONTROL INTERNO', 'AGROECOSISTEMAS',
       'REDES INALÁMBRICAS Y DE SENSORES', 'INVESTIGACIÓN DE MERCADOS',
       'SISTEMAS DE INFORMACIÓN APLICADOS A LOGÍSTICA',
       'DISEÑO DE BUQUES', 'INGENIERÍA DE YACIMIENTOS II',
       'GESTIÓN DE LA CADENA DE SUMINISTRO SOSTENIBLE',
       'PROGRAMACIÓN ORIENTADA A OBJETOS', 'TERMODINÁMICA',
       'MECÁNICA DE FLUIDOS',
       'ANÁLISIS DE FALLAS Y SELECCIÓN DE MATERIALES', 'DISEÑO DE MARCA',
       'COMUNICACIONES INDUSTRIALES Y SISTEMAS SCADA',
       'PROCESOS DE MANUFACTURA', 'MATEMÁTICAS FINANCIERAS',
       'RESISTENCIA DE MATERIALES', 'DISEÑO DE SONIDO',
       'TENDENCIAS EN NUTRICIÓN',
       'INTRODUCCIÓN A LA HISTORIA Y ETNOHISTORIA',
       'DISEÑO DE SISTEMAS MECÁNICOS', 'PROTECCIONES ELÉCTRICAS',
       'INTRODUCCIÓN A LA INGENIERÍA EN MATERIALES',
       'INSTRUMENTACIÓN INDUSTRIAL', 'ELECTRÓNICA DE POTENCIA II',
       'INGENIERÍA DE TRÁNSITO', 'DERECHO ECONÓMICO',
       'FUNDAMENTOS DE ELECTRICIDAD Y SISTEMAS DIGITALES',
       'ESTRUCTURA Y CARACTERIZACIÓN DE MATERIALES',
       'VENTILACIÓN, DRENAJE Y SISTEMAS ELÉCTRICOS',
       'SISTEMAS DE CONTROL', 'SISTEMAS DIGITALES II',
       'QUÍMICA ALIMENTARIA', 'PRINCIPIOS DE ELECTRÓNICA',
       'SISTEMAS FLEXIBLES DE MANUFACTURA', 'SEGURIDAD DE LA INFORMACIÓN',
       'APLICACIONES ELECTRÓNICAS', 'DINÁMICA DEL BUQUE',
       'INGENIERÍA DE LA CONSTRUCCIÓN', 'INGENIERÍA DE LA CALIDAD',
       'INSTRUMENTACIÓN', 'DISEÑO DE CAMPO GEOLÓGICO',
       'DIRECCIÓN DE PROYECTOS INFORMÁTICOS',
       'EVALUACIÓN DE PROYECTOS HIDROCARBURÍFEROS',
       'LENGUAJES DE PROGRAMACIÓN', 'ESTRUCTURAS METÁLICAS',
       'PROGRAMACIÓN DE SISTEMAS', 'SERIES DE TIEMPO',
       'PROGRAMACIÓN ENTERA PARA INGENIERÍA',
       'PROCESAMIENTO DE FARINÁCEOS Y OLEAGINOSAS',
       'DISEÑO DE PRODUCCIÓN',
       'HISTORIA Y FILOSOFÍA DEL PENSAMIENTO ECONÓMICO', 'SOCIOLOGÍA',
       'HORMIGÓN PREFORZADO', 'TALLER DE DISEÑO II',
       'DISTRIBUCIÓN ELÉCTRICA I', 'ORGANIZACIÓN INDUSTRIAL',
       'DISEÑO GRÁFICO I', 'ELECTRÓNICA',
       'AUTOMATIZACIÓN DE PROCESOS INDUSTRIALES', 'ALIMENTOS Y BEBIDAS',
       'PLANIFICACIÓN Y CONSTRUCCIÓN', 'MATEMÁTICAS DISCRETAS',
       'SISTEMAS DIGITALES I', 'DISEÑO DE VÍAS',
       'MORFOFISIOLOGÍA HUMANA II',
       'CAMPO DE ANTROPOLOGÍA SOCIOCULTURAL I', 'CONTABILIDAD DE COSTOS',
       'DESARROLLO DE NUEVOS PRODUCTOS ALIMENTICIOS', 'FÍSICA GENERAL',
       'INTERNETWORKING', 'PROPAGACIÓN', 'PROYECTO AUDIOVISUAL II',
       'MINERALURGIA Y METALURGIA EXTRACTIVA', 'HIDRÁULICA Y NEUMÁTICA',
       'TERMOFLUIDOS', 'DISEÑO ESTRUCTURAL', 'OPTIMIZACIÓN LINEAL',
       'MATEMÁTICAS', 'INVESTIGACIÓN AUDIOVISUAL',
       'GESTIÓN DE ZONAS MARINO-COSTERAS', 'LEGISLACIÓN AUDIOVISUAL',
       'FORMAS E HIDROSTÁTICA DEL BUQUE', 'PLANEAMIENTO Y DISEÑO MINERO',
       'PROCESOS ESTOCÁSTICOS', 'ANÁLISIS DE INFORMACIÓN OCEANOGRÁFICA',
       'OPERACIONES UNITARIAS II', 'TEORÍA DE LA COMUNICACIÓN',
       'GESTIÓN COMERCIAL', 'COMERCIO EXTERIOR',
       'MÁQUINAS Y TRANSFORMADORES',
       'INTRODUCCIÓN A LA INGENIERÍA INDUSTRIAL', 'SIMULACIÓN',
       'INGENIERÍA DE PRODUCCIÓN II', 'OPERACIÓN DE SISTEMAS DE POTENCIA',
       'FIBRAS ÓPTICAS', 'SISTEMAS EN LA NUBE',
       'MODELIZACIÓN DEL TRANSPORTE',
       'METODOLOGÍA DE LA INVESTIGACIÓN EN COMPUTACIÓN',
       'GESTIÓN MARÍTIMA PORTUARIA', 'ADMINISTRACIÓN LOGÍSTICA',
       'FOTOGRAFÍA PARA MEDIOS', 'AUDITORÍA FINANCIERA II',
       'ECONOMÍA MATEMÁTICA', 'SISTEMAS DE COMUNICACIONES II',
       'SISTEMAS DE REDES', 'VULNERABILIDAD Y RIESGO GEOLÓGICO',
       'MÉTODOS ROBUSTOS Y NO PARAMÉTRICOS', 'GESTIÓN DE DRAGADOS',
       'CÁLCULO II', 'MEDIDA Y PROBABILIDAD', 'SALUD COMUNITARIA',
       'TOXICOLOGÍA NUTRICIONAL Y ALIMENTARIA', 'NUTRICIÓN CLÍNICA I',
       'MINERALOGÍA', 'AGRICULTURA DE PRECISIÓN', 'NUTRICIÓN CLÍNICA III',
       'SISTEMAS Y PROGRAMACIÓN DE PRODUCCIÓN',
       'GESTIÓN DE INFRAESTRUCTURA Y SERVICIOS TI',
       'ADMINISTRACIÓN DE OPERACIONES', 'ANÁLISIS ESTRUCTURAL',
       'TRANSPORTE MARÍTIMO', 'DATOS NO ESTRUCTURADOS',
       'AUDITORÍA DE SISTEMAS INTEGRADOS',
       'NUTRICIÓN EN EL CICLO DE LA VIDA II', 'NUTRICIÓN CLÍNICA II',
       'ANÁLISIS NUTRICIONAL DE LOS ALIMENTOS',
       'ESTADÍSTICA MULTIVARIANTE', 'REDES DE DATOS',
       'SERVICIOS DE ALIMENTACIÓN',
       'METODOLOGÍAS PARA LA MEJORA CONTINUA',
       'SISTEMAS DE CONTROL DE PRODUCCIÓN', 'TALLER MECÁNICO',
       'EVALUACIÓN DE FORMACIONES II', 'PREPRODUCCIÓN',
       'APRENDIZAJE ESTADÍSTICO', 'SISTEMAS DE TRANSPORTE',
       'DISEÑO DE MATERIALES COMPUESTOS', 'DISEÑO DE SOFTWARE',
       'GEOGRAFÍA FÍSICA', 'CONSTRUCCIÓN DE OBRAS PORTUARIAS',
       'ANTROPOLOGÍA NUTRICIONAL', 'ESTÁTICA', 'PROCESOS DE MECANIZACIÓN',
       'PERFORACIÓN', 'DISEÑO COSTERO', 'INSTALACIONES',
       'MECÁNICA DE SÓLIDOS', 'EVALUACIÓN Y SIMULACIÓN DE REDES',
       'CONSEJERÍA NUTRICIONAL', 'LABORATORIO DE ARQUEOLOGÍA II',
       'GEOMÁTICA MINERA', 'PLANIFICACIÓN DE DRAGADOS',
       'GEOLOGÍA ESTRUCTURAL', 'CONTROLES ELÉCTRICOS INDUSTRIALES',
       'MODELOS ESTADÍSTICOS APLICADOS I', 'GEOMECÁNICA',
       'BIOQUÍMICA ALIMENTARIA', 'EVALUACIÓN DE YACIMIENTOS MINERALES',
       'SISTEMAS BIOMECATRÓNICOS', 'ANÁLISIS DE REDES ELÉCTRICAS',
       'MICROECONOMÍA I', 'OCEANOGRAFÍA FÍSICA',
       'ARQUEOLOGÍA DEL ECUADOR I', 'NUTRICIÓN EN EL CICLO DE LA VIDA I',
       'INGENIERÍA DE SOFTWARE I', 'GUION',
       'LÍNEAS DE TRANSMISIÓN Y SUBESTACIONES',
       'IMPACTO AMBIENTAL MARINO-COSTERO', 'CENTRALES ELÉCTRICAS',
       'COMPUTACIÓN Y SOCIEDAD', 'CAMPO DE ANTROPOLOGÍA SOCIOCULTURAL II',
       'NUTRICIÓN HUMANA Y METABOLISMO',
       'SISTEMAS DE RECOLECCIÓN Y DISTRIBUCIÓN DE AGUA',
       'COMPLETACIÓN Y REACONDICIONAMIENTO DE POZOS',
       'DISEÑO MECATRÓNICO', 'SISTEMAS DE MONITOREO Y CONTROL INDUSTRIAL',
       'PLANIFICACIÓN Y CONTROL FINANCIERO',
       'GESTIÓN Y MARCO REGULATORIO DEL SECTOR ELÉCTRICO',
       'REOLOGÍA DE FLUIDOS', 'PRÁCTICA TRIBUTARIA', 'GEOESTADISTICA',
       'CIRCUITOS ELÉCTRICOS', 'GESTIÓN DEL DISEÑO',
       'MAQUINARIA MARÍTIMA I', 'GESTIÓN DE OBRAS CIVILES',
       'GEOTECNIA MINERA', 'ACTUADORES MECATRÓNICOS',
       'ROBOTS MÓVILES Y ARTICULADOS',
       'TURBOMAQUINARIA Y PLANTAS DE POTENCIA', 'PROYECTOS AGRÍCOLAS',
       'DISEÑO DE PAVIMENTOS', 'HORMIGÓN Y MATERIALES DE CONSTRUCCIÓN',
       'PROTOTIPADO AVANZADO', 'MÉTODOS DE ANALÍTICA PARA LA INDUSTRIA',
       'DESARROLLO SOSTENIBLE DEL TURISMO',
       'ARQUEOLOGÍA SOCIAL LATINOAMERICANA',
       'INTRODUCCIÓN A LA MECATRÓNICA', 'LOGÍSTICA Y SERVICIO AL CLIENTE',
       'OCEANOGRAFÍA DESCRIPTIVA',
       'ORÍGENES DE LOS ESTADOS PREHISPÁNICOS',
       'COMPORTAMIENTO ORGANIZACIONAL', 'SANIDAD E HIGIENE ALIMENTARIA',
       'ECONOMÍA GERENCIAL', 'INTRODUCCIÓN A LA ESTADÍSTICA',
       'HIDROGEOLOGÍA', 'DEPÓSITOS MINERALES',
       'MECÁNICA DE MATERIALES GEOLÓGICOS', 'CLIMATOLOGÍA Y METEOROLOGÍA',
       'FENÓMENOS DE TRANSPORTE DE CALOR',
       'ELECTRICIDAD Y ELECTRÓNICA PARA BUQUES', 'GEOLOGÍA GENERAL',
       'MATEMÁTICAS SUPERIORES', 'GEOMETRÍA DIFERENCIAL',
       'INTRODUCCIÓN A LA MANUFACTURA',
       'ELEMENTOS DE COMPUTACIÓN CIENTÍFICA',
       'ADMINISTRACIÓN DE SISTEMAS Y SERVICIOS EN RED',
       'CIENCIA E INGENIERÍA DE MATERIALES', 'ESTRUCTURA DEL BUQUE',
       'TÉCNICAS PICTÓRICAS', 'DIRECCIÓN ESCÉNICA', 'MECÁNICA VECTORIAL',
       'SISTEMAS DE CONTROL DE GESTIÓN', 'GEOLOGIA DE ECUADOR',
       'FINANZAS INTERNACIONALES',
       'GESTIÓN DE PROYECTOS Y REGULACIÓN EN TELECOMUNICACIONES',
       'TALLER DE ILUSTRACIÓN', 'ÁLGEBRA LINEAL',
       'INGENIERÍA DE CIMENTACIÓN', 'DISTRIBUCIÓN ELÉCTRICA II',
       'MACROECONOMÍA II', 'OPTIMIZACIÓN COMBINATORIA',
       'ANÁLISIS DE VALOR DE PRODUCTO', 'CONGRESOS Y EVENTOS',
       'TERMODINÁMICA DE MATERIALES', 'AUDITORÍA FINANCIERA I',
       'SISTEMAS DE POTENCIA II', 'INGENIERÍA DE CERÁMICOS',
       'CONTABILIDAD III', 'MICROECONOMÍA II', 'ANÁLISIS COMPLEJO',
       'ANIMACIÓN I', 'PRODUCCIÓN PARA NUEVOS MEDIOS', 'PORTAFOLIO',
       'ECUACIONES DIFERENCIALES',
       'PROGRAMACIÓN APLICADA A LA AUTOMATIZACIÓN',
       'TÉCNICAS DE MUESTREO Y ANÁLISIS MULTIVARIADO',
       'MICROECONOMÍA III', 'DERECHO SOCIETARIO Y LABORAL',
       'DISEÑO Y SIMULACIÓN DE MÁQUINAS', 'FUNDAMENTOS DE OPTIMIZACIÓN',
       'CRECIMIENTO Y DESARROLLO ECONÓMICO', 'TALLER DE DISEÑO III',
       'INTRODUCCIÓN A LA ANTROPOLOGÍA Y ARQUEOLOGÍA',
       'FUNDAMENTOS DE MARKETING', 'MÉTODOS DE INVESTIGACIÓN EN TURISMO',
       'EVALUACIÓN DEL ESTADO NUTRICIONAL II', 'HISTORIA DEL DISEÑO',
       'SISTEMA DE BASES DE DATOS', 'CONTROL AVANZADO',
       'FERMENTACIÓN Y ENZIMOLOGÍA ALIMENTARIA',
       'DIBUJO TÉCNICO Y PLANOS', 'NARRATIVA AUDIOVISUAL', 'GEOMÁTICA',
       'SISTEMAS DE COMUNICACIONES I', 'ESTRUCTURAS DE DATOS',
       'DISEÑO GRÁFICO II', 'PROGRAMACIÓN DE SISTEMAS TELEMÁTICOS',
       'TEORÍA DEL TURISMO', 'MORFOFISIOLOGÍA HUMANA I', 'DIBUJO II',
       'TEORÍA ELECTROMAGNÉTICA', 'PATRIMONIO NATURAL Y CULTURAL',
       'TALLER DE DISEÑO I', 'ÁLGEBRA LINEAL II',
       'DISEÑO DE PRODUCTOS II',
       'INTRODUCCIÓN A LAS TÉCNICAS DE AUDITORÍA',
       'MÉTODOS MATEMÁTICOS PARA LAS CIENCIAS', 'HIDROLOGÍA',
       'ANÁLISIS FUNCIONAL', 'ARQUEOLOGÍA DE MESOAMÉRICA',
       'DERECHO TRIBUTARIO', 'HISTORIA DEL CINE',
       'ORGANIZACIÓN DE COMPUTADORES', 'DISEÑO DIGITAL',
       'DISEÑO DE PRODUCTOS I', 'MICROBIOLOGÍA DE ALIMENTOS',
       'LEGISLACIÓN Y SOBERANÍA ALIMENTARIA', 'PRESUPUESTO',
       'DISEÑO DE ELEMENTOS DE MÁQUINAS', 'TIPOGRAFÍA',
       'PERFORACIÓN Y VOLADURA', 'PLANIFICACIÓN DE ESPACIOS TURÍSTICOS',
       'DISEÑO DE PROCESOS TÉRMICOS I',
       'DIAGNÓSTICO Y PROTECCIÓN VEGETAL I', 'SISTEMAS DE POTENCIA I',
       'DISEÑO GRÁFICO III', 'ÁLGEBRA LINEAL I', 'ERGONOMÍA',
       'FUNDAMENTOS DE AUDITORÍA', 'CONTROL ESTADÍSTICO DE PROCESOS',
       'MATERIALES Y MANUFACTURA II', 'ANÁLISIS NUMÉRICO',
       'FUNDAMENTOS DE PLANIFICACIÓN TURÍSTICA',
       'SEGURIDAD Y SALUD OCUPACIONAL', 'PETROGRAFÍA',
       'PRODUCCIÓN PECUARIA I', 'FÍSICA: TERMODINÁMICA Y ELECTRÓNICA',
       'PETROLOGÍA ÍGNEA Y METAMÓRFICA',
       'DESARROLLO DE APLICACIONES WEB Y MÓVILES',
       'DISEÑO DE PRODUCTOS III',
       'PROPIEDADES DE HIDROCARBUROS Y COMPORTAMIENTO DE FASES',
       'MECÁNICA DE SUELOS Y ROCAS', 'GESTIÓN DE LA PRODUCTIVIDAD',
       'LOGÍSTICA II', 'MATERIALES Y MANUFACTURA III',
       'MODELADO TRIDIMENSIONAL', 'MAQUINARIA ELÉCTRICA I',
       'ESTRATIGRAFIA Y SEDIMENTACIÓN', 'PROCESOS INDUSTRIALES',
       'MATERIALES EN MEDIOS MARINOS', 'ANÁLISIS DE ALIMENTOS',
       'DINÁMICA', 'SÍNTESIS DE MATERIALES',
       'ARQUEOLOGÍA DE LAS TIERRAS BAJAS DE SUDAMÉRICA Y DEL CARIBE',
       'VIDEOGRAFÍA', 'EXTENSIONISMO', 'TOPOGRAFÍA',
       'ARQUEOLOGÍA DEL ECUADOR II', 'MATEMÁTICAS AVANZADAS',
       'INOCUIDAD ALIMENTARIA',
       'CIRCUITOS DE ALTA FRECUENCIA Y MICROONDAS',
       'EVALUACIÓN DE FORMACIONES I', 'PETROLOGIA SEDIMENTARIA',
       'INGENIERÍA DE DATOS', 'TRANSFERENCIA DE CALOR Y MASA',
       'SILVICULTURA', 'EDAFOLOGÍA',
       'DIAGNÓSTICO Y PROTECCIÓN VEGETAL II', 'GENÉTICA',
       'PRODUCCIÓN VEGETAL III', 'PRODUCCIÓN VEGETAL I',
       'RIEGO Y DRENAJE', 'PRODUCCIÓN VEGETAL II', 'GENOTECNIA',
       'PRODUCCIÓN PECUARIA II', 'SEMILLEROS Y VIVEROS',
       'BOTÁNICA GENERAL', 'FUNDAMENTOS DE LA INGENIERÍA EN ALIMENTOS',
       'INGENIERÍA DE PROCESOS ALIMENTARIOS', 'PROCESAMIENTO DE LÁCTEOS',
       'PROCESAMIENTO DE FRUTAS Y VEGETALES',
       'DISEÑO DE PROCESOS TÉRMICOS II', 'ANTROPOLOGÍA BIOLÓGICA',
       'DISEÑO DE PRODUCTOS IV', 'TEORÍA ANTROPOLÓGICA Y ARQUEOLÓGICA',
       'ARQUEOLOGÍA ANDINOAMERICANA', 'BIOARQUEOLOGÍA',
       'LABORATORIO DE ARQUEOLOGÍA I',
       'ESTUDIO DE CASOS DE CIENCIAS SOCIALES',
       'PROYECTOS DE INVESTIGACIÓN ARQUEOLÓGICA',
       'CAMPO DE ARQUEOLOGÍA I', 'ARQUEOLOGÍA DEL VIEJO MUNDO',
       'PRIMER POBLAMIENTO AMERICANO', 'INGENIERÍA GEOLÓGICA',
       'TÉCNICAS DE IMPRESIÓN', 'ANIMACIÓN II',
       'HISTORIA DEL DISEÑO INDUSTRIAL', 'TEORÍA DEL DISEÑO',
       'INVESTIGACIÓN APLICADA AL DISEÑO', 'ESTRUCTURAS Y MECANISMOS I',
       'AUDITORÍA DE SISTEMAS DE INFORMACIÓN', 'MUESTREO',
       'CONTABILIDAD I', 'GESTIÓN DE RECURSOS HUMANOS',
       'DESARROLLO ORGANIZACIONAL', 'TÉCNICAS CULINARIAS',
       'FARMACOLOGÍA Y NUTRICIÓN', 'EVALUACIÓN DEL ESTADO NUTRICIONAL I',
       'BIOÉTICA', 'GESTIÓN DE MARKETING', 'MACROECONOMÍA III',
       'SEÑALES Y SISTEMAS',
       'MODELOS ESTOCÁSTICOS PARA MANUFACTURA Y SERVICIOS',
       'ANTROPOLOGÍA DEL DISEÑO', 'ANÁLISIS DE ALGORITMOS',
       'ECONOMETRÍA II', 'ESTRUCTURAS ALGEBRAICAS', 'CÁLCULO I',
       'ANÁLISIS MATEMÁTICO I',
       'ESTABILIDAD Y CONTROL DE SISTEMAS DE POTENCIA',
       'MATERIALES Y MANUFACTURA I', 'MECÁNICA DE MAQUINARIA',
       'GEOGRAFÍA TURÍSTICA', 'TRANSFORMACIONES DE FASES',
       'NANOTECNOLOGÍA Y NANOMATERIALES', 'NUTRICIÓN DEPORTIVA',
       'ESTRUCTURAS Y MECANISMOS II', 'TRANSFERENCIA DE CALOR',
       'HIDRÁULICA', 'FENÓMENOS DE TRANSPORTE DE MASA',
       'MAQUINARIA ELÉCTRICA II', 'ANÁLISIS DISCRETO',
       'ECUACIONES DIFERENCIALES I',
       'TELEMÁTICA Y TRANSFORMACIÓN DIGITAL', 'OPERACIÓN DE COMPUTADORES',
       'OCEANOGRAFÍA COSTERA', 'TALLER DE DISEÑO IV',
       'PERFORACIÓN DIRECCIONAL', 'PRONÓSTICO Y CONTROL DE INVENTARIO',
       'CONSERVACIÓN Y MANEJO AMBIENTAL EN TURISMO', 'TRANSPORTE URBANO',
       'PROPIEDADES  FUNCIONALES DE LOS  MATERIALES',
       'CONTROLES ELÉCTRICOS', 'MÁQUINAS ELÉCTRICAS',
       'INGENIERÍA DE YACIMIENTOS I', 'MAQUINARIA MARÍTIMA II',
       'TERMODINÁMICA II', 'LOGÍSTICA I', 'ESTADÍSTICA MATEMÁTICA',
       'ESTADÍSTICA COMPUTACIONAL', 'DATOS CATEGÓRICOS',
       'DISEÑO DE EXPERIMENTOS', 'OPTIMIZACIÓN NO LINEAL Y ESTOCÁSTICA',
       'TRANSPORTE MULTIMODAL',
       'DISEÑO Y MANUFACTURA ASISTIDA POR COMPUTADORA',
       'TEORÍA DE LA MEDIDA', 'ECUACIONES DIFERENCIALES II',
       'TÉCNICAS DIETÉTICAS', 'FUNDAMENTOS DE MINERÍA',
       'GEOMETRÍA AXIOMÁTICA', 'PALEONTOLOGÍA APLICADA',
       'FÍSICA: TERMODINÁMICA Y ÓPTICA', 'MÉTODOS GEOFÍSICOS',
       'GEOMORFOLOGIA', 'GEOLOGÍA DEL PETRÓLEO', 'MINERALOGÍA ÓPTICA',
       'TECTONICA', 'LEGISLACIÓN Y MITIGACIÓN AMBIENTAL',
       'INTRODUCCIÓN A LA INDUSTRIA HIDROCARBURÍFERA',

In [35]:
df_materias_xslx["CodigoMateria"].nunique() - df_new_semester["COD_MATERIA_ACAD_MO"].nunique()

86

In [56]:
df_materias_xslx_faltantes = df_materias_xslx[~df_materias_xslx["CodigoMateria"].isin(df_new_semester["COD_MATERIA_ACAD_MO"].unique())].copy()
df_materias_xslx_faltantes["NombreMateria"]

20                    MATERIA INTEGRADORA DE ACUICULTURA
22                           EMPRENDIMIENTO E INNOVACIÓN
23     GESTIÓN DE PROYECTOS Y REGULACIÓN EN TELECOMUN...
24                                ESTRATEGIAS DE GESTIÓN
25                         ADMINISTRACIÓN DE OPERACIONES
                             ...
675            MATERIA INTEGRADORA DE INGENIERÍA QUÍMICA
686            MATERIA INTEGRADORA DE TELECOMUNICACIONES
695                             BASES DE DATOS AVANZADAS
703                    MATERIA INTEGRADORA DE TELEMÁTICA
717                       MATERIA INTEGRADORA DE TURISMO
Name: NombreMateria, Length: 86, dtype: object

In [37]:
missing_rows = df_materias_xslx[
    ~df_materias_xslx["CodigoMateria"].isin(df_new_semester["COD_MATERIA_ACAD_MO"])
]

len(missing_rows)  # filas (posible 86)
missing_rows["CodigoMateria"].nunique()  # códigos únicos faltantes (posible 70)

86

In [38]:
faltan_en_new = set(df_materias_xslx["CodigoMateria"].dropna().astype(str).str.strip()) - \
                set(df_new_semester["COD_MATERIA_ACAD_MO"].dropna().astype(str).str.strip())

len(faltan_en_new)

86

In [39]:
# ADMG2035  este da error

In [40]:
lista_error = ['EYAT3004', 'MING1029', 'MING1036', 'GEOG1038', 'LOGG1021', 'AUDG2044', 'ESTG1055', 'AGRG1040', 'NAVT3001', 'GEOG1051', 'LOGT3002', 'CCPG1041', 'GEOG1028', 'TLMG1026', 'MATG1077', 'NAVG1027', 'GEOG1029', 'MING1027', 'MECT3002', 'ESTG1049', 'OCEG1047', 'ARQG2028', 'GEOG1035', 'MING1041', 'MING1024', 'ESTG1057', 'MING1034', 'ARQG2036', 'OCEG1029', 'OCEG1029', 'OCEG1029', 'OCEG1029', 'OCEG1049', 'TELG1029', 'CCPT3004', 'OCEG1040', 'ELET3001', 'MATG1074', 'LOGG1022', 'AGRG1030', 'MECT3003', 'MCTT3011', 'EYAT3002', 'ESTG1050', 'ARQG2029', 'ESTT3002', 'LOGT3010', 'ARQG2023', 'MCTT3015', 'MATG1071', 'LOGT3009', 
               'OCEG1033', 'LOGT3006', 'IDIT3004', 'LOGG1024', 'OCEG1034', 'MING1033', 'MATG1060', 'LOGG1020', 'NAVT3003', 'OCEG1035', 'PETG1021', 'MING1025', 'ARQG2030', 'MATG1067', 'OCEG1031', 'OCEG1046', 'LOGG1023', 'OCEG1051', 'GEOG1048', 'INDG1060', 'ARQG2022', 'EYAT3003', 'ESTG1054', 'OCET3002', 'ELET3002', 'TELG1034', 'OCEG1039', 'ARQG2043', 'AGRG1022', 'JURG2005', 'OCEG1038', 'ESTG1047', 'ECOG2058', 'TELG1038', 'ESTG1048', 'LOGT3012', 'MING1040', 'LOGT3011', 'ESTG1033', 'MATG1069', 'IDIT3003', 'NAVG1031', 'TURG2030', 'MCTT3014', 'LOGT3013', 'AGRG1028', 'ADST3002', 'TURG2031', 'GEOG1040', 'NAVG1025', 'NAVT3002', 'ECOG1008', 'TLMG1025', 'LOGT3007']

lista_error = ['ACUG1058', 'ADMG1005', 'ADMG1006', 'ADMG1007', 'ADMG2022', 'ADMG2024', 'ADMG2025', 'ADMG2026', 'ADMG2028', 'ADMG2029', 'ADMG2030', 'ADMG2031', 'ADMG2032', 'ADMG2033', 'ADMG2034', 'ADMG2035', 'ADMG2036', 'ADMG2037', 'ADMT3004', 'ADMT3004', 'ADST3002', 'ADST3002', 'AGRG1022', 'AGRG1028', 'AGRG1029', 'AGRG1030', 'AGRG1040', 'ALIG1040', 'ARQG2022', 'ARQG2023', 'ARQG2024', 'ARQG2028', 'ARQG2030', 'ARQG2036', 'ARQG2043', 'AUDG2040', 'BIOG1027', 'CADG2043', 'CCPG1035', 'CCPT3004', 'CCPT3004', 'CDIAG1001', 'CDIAG1001', 'CDIAG1002', 'CDIAG1002', 'CDIAG1003', 'CDIAG1802', 'CDIAG1802', 'CDIAG1804', 'CDIAG1804', 'CDIAG1806', 'CDIAG1806', 'CDIAG1807', 
               'CDIAG1807', 'CDIAG1808', 'CDIAG1808', 'CDIAG1809', 'CDIAG1809', 'CIVG1054', 'DIGG2034', 'DING2032', 'ECOG1008', 'ECOG2053', 'ELEG1042', 'ELET3001', 'ELET3001', 'ELET3002', 'ELET3002', 'ESTG1047', 'ESTG1048', 'ESTG1049', 'ESTG1050', 'ESTG1055', 'ESTG1057', 'ESTG1062', 'ESTG1801', 'ESTG1801', 'ESTT3002', 'ESTT3002', 'EYAG1039', 'EYAT3002', 'EYAT3003', 'EYAT3004', 'EYAT3004', 'GEOG1028', 'GEOG1029', 'GEOG1035', 'GEOG1038', 'GEOG1039', 'GEOG1040', 'GEOG1048', 'GEOG1051', 'IDIG1801', 'IDIG1801', 'IDIT3003', 'IDIT3003', 'IDIT3004', 'IDIT3004', 'INDG1043', 'LOGG1020', 'LOGG1023', 'LOGG1024', 'LOGG1027', 'LOGT3002', 'LOGT3002', 'LOGT3006', 'LOGT3006', 
               'LOGT3007', 'LOGT3007', 'LOGT3009', 'LOGT3009', 'LOGT3010', 'LOGT3010', 'LOGT3011', 'LOGT3011', 'LOGT3012', 'LOGT3012', 'LOGT3013', 'LOGT3013', 'LOGT3014', 'LOGT3014', 'MATG1060', 'MATG1067', 'MATG1069', 'MATG1071', 'MATG1074', 'MATG1077', 'MATG1086', 'MCTG1028', 'MCTT3011', 'MCTT3014', 'MCTT3014', 'MCTT3015', 'MCTT3015', 'MCTT3017', 'MCTT3017', 'MECG1066', 'MECT3002', 'MECT3003', 'MECT3003', 'MING1024', 'MING1025', 'MING1027', 'MING1029', 'MING1033', 'MING1034', 'MING1040', 'MING1041', 'MTRG1034', 'NAVG1025', 'NAVG1027', 'NAVG1031', 'NAVG1034', 'NAVT3001', 'NAVT3001', 'NAVT3002', 'NAVT3002', 'NAVT3003', 'NAVT3003', 'NUTG2031', 'OCEG1033', 'OCEG1035', 
               'OCEG1038', 'OCEG1039', 'OCEG1040', 'OCEG1043', 'OCEG1043', 'OCEG1046', 'OCEG1047', 'OCEG1049', 'OCEG1051', 'OCET3002', 'OCET3002', 'PETG1021', 'PETG1033', 'QUIG1050', 'TELG1033', 'TELG1034', 'TELG1038', 'TICG1801', 'TICG1801', 'TLMG1025', 'TLMG1026', 'TLMG1031', 'TURG2029']

In [41]:
len(lista_error)

185

In [42]:
df_materias_xslx["CodigoMateria"].nunique()-len(lista_error)

541

hay una materia que aprobaron todos y nadie a visto la prerequisito, entonces no tiene estudiantes nuevos  
EYAT3004, MECT3003

In [43]:
list_encoder = ['ARQG2039', 'ADST3002', 'AGRG1035', 'ELEG1051', 'CCPG1801', 'CIVG1049', 'MTRG1039', 'LOGT3011', 'ARQG2040', 'ARQG2030', 'MATG1073', 'ALIG1044', 'OCEG1048', 'EYAG1027', 'QUIG1034', 'EYAT3004', 'CIVG1055', 'ARQG2036', 'MEDG1024', 'MCTT3011', 'BIOG1026', 'DING2028', 'ACUG1039', 'GEOG1026', 'ELET3002', 'ADSG1029', 'MCTG1022', 'NUTG2030', 'OCEG1031', 'NUTG2036', 'DING2036', 'ACUG1036', 'AGRG1022', 'MEDG2012', 'PETG1034', 'TURG2018', 'AUDG2041', 'ESTG1056', 'EYAG1046', 'CIVG1035', 'NUTG2035', 'PETG1022', 'ARQG2041', 'CCAG2021', 'ESTG1047', 'ALIG1029', 'NAVT3003', 'ELET3004', 'LOGG1023', 'ECOG2067', 'DING2034', 'CCPG1041', 'ALIG1045', 'LOGG1024', 'MCTG1021', 'MING1026', 'EYAG1028', 'MTRG1031', 'INDG1054', 'CIVG1060', 'LOGG1021', 'INDT3002', 'ECOG2047', 'OCEG1032', 'LOGT3013', 'AUDG2034', 'BIOG1022', 'EYAG1043', 'ARTG2028', 'AGRG1030', 'ALIG1035', 'TLMG1025', 'OCEG1037', 'DIGG2041', 'GEOG1046', 'AGRG1041', 'MING1036', 'MATG1074', 'AUDG2042', 'GEOG1042', 'EYAG1035', 'MATG1059', 'TLMG1030', 'NAVG1033', 'ARTG2030', 'TURG2032', 'ESTG1055', 'OCEG1028', 'ARTG2024', 'TELG1037', 'GEOG1040', 'PETG1032', 'ELEG1036', 'ESTT3003', 'DIGG2035', 'MECG1054', 'CCPG1042', 'NAVG1042', 'TLMG1028', 'AGRG1037', 'TURG2036', 'CCPG1052', 'ECOG2045', 'DING2038', 'NUTG2043', 'MECT3001', 'MCTG1011', 'ACUG1045', 'AUDG2027', 'MING1029', 'IDIT3003', 'LOGG1019', 'ALIG1036', 'EYAG1040', 'MING1040', 'TLMG1034', 'CADG2045', 'CIVG1053', 'DIGG2025', 'LOGT3010', 'MATG1055', 'MEDG1026', 'OCEG1044', 'INDG1055', 'MECG1064', 'MECG1047', 'NAVG1030', 'CCPG1054', 'GEOG1034', 'INDG1044', 'MEDG2013', 'AGRG1023', 'GEOG1047', 'ACUG1054', 'HISG2002', 'EDCOM00281', 'AUDG2030', 'MATG1067', 'CADG2031', 'COMG2002', 'INDG1052', 'NUTG2028', 'ECOG2065', 'ECOG2055', 'CIVG1037', 'INDG1039', 'TURG2034', 'TURG2035', 'MTRG1041', 'FISG2002', 'ADSG1022', 'ARQG2022', 'CIVG1044', 'GEOG1029', 'MECG1044', 'MECG1056', 'MATG1056', 'CCPT3004', 'ACUG1050', 'NAVG1029', 'ALIG1034', 'FISG1008', 'CCPG1053', 'MECG1052', 'ECOG2043', 'GEOG1052', 'CIVG1045', 'MECG1042', 'EYAG1034', 'IDIG1802', 'AGRG1032', 'ALIG1047', 'MEDG2020', 'NAVG1037', 'MATG1071', 'NUTG2038', 'EYAG1044', 'LOGT3012', 'NAVT3001', 'CADG2033', 'ESTG1035', 'AUDG2035', 'EYAT3003', 'CIVG1039', 'MATG1054', 'AUDG2036', 'CCPG1055', 'ESTG1051', 'ECOG2042', 'ECOG2060', 'INDG1033', 'CCPG1056', 'IDIG1007', 'ELEG1035', 'MECG1057', 'IDIT3004', 'PETG1021', 'ARQG2033', 'LOGG1016', 'TLMG1022', 'ELEG1039', 'MATG1045', 'CCPG1048', 'MING1033', 'DING2024', 'ACUG1046', 'GEOG1051', 'ELEG1031', 'ELEG1033', 'DIGG2028', 'ECOG2051', 'ACUG1052', 'MECG1045', 'ARQG2032', 'ELEG1034', 'MATG2007', 'CADG2046', 'MATG1057', 'QUIG1044', 'BIOG1030', 'MATG1049', 'INDG1040', 'MECG1060', 'TELG1030', 'MATG1052', 'BIOG1024', 'ELEG1046', 'EYAG1030', 'AUDG2038', 'MING1025', 'EYAG1041', 'NUTG2041', 'IDIG1806', 'MATG1082', 'CIVG1034', 'MING1030', 'MECG1048', 'MATG1080', 'CCPT3003', 'LOGT3006', 'MTRG1037', 'DIGG2036', 'MING1041', 'MECT3003', 'QUIG1038', 'AGRG1039', 'MECG1068', 'ACUG1042', 'ELEG1028', 'MECG1061', 'MATG1063', 'AGRG1040', 'NUTG2039', 'ADSG1020', 'JURG2005', 'ECOG2058', 'INDG1057', 'MEDG1018', 'MATG1070', 'MCTG1018', 'MING1037', 'IDIG1008', 'AGRG1036', 'AUDG2037', 'MCTG1019', 'ECOG2064', 'ARTG2023', 'ECOG1008', 'EYAG1038', 'PETG1020', 'ESTG1046', 'CIVG1041', 'MATG1066', 'ALIG1039', 'CCPG1058', 'QUIG1043', 'MEDG1025', 'MATG1075', 'OCEG1029', 'DING2030', 'ARTG2033', 'ESTG1044', 'ESTG1038', 'ARTG2025', 'GEOG1031', 'AUDG2032', 'QUIG1035', 'ARQG2023', 'TELG1031', 'CADG2042', 'MATG1061', 'MTRG1040', 'BIOG1029', 'NAVG1031', 'NUTG2032', 'SOFG1008', 'GEOG1036', 'ECOG2054', 'DING2029', 'MTRG1030', 'INDG1041', 'ACUG1059', 'PETG1031', 'MING1032', 'DIGG2037', 'MEDG1023', 'TICG1802', 'ECOG2046', 'OCEG1039', 'AUDG2043', 'ESTG1045', 'CADG2026', 'ARQG2035', 'ESTG1042', 'ELEG1030', 'EYAG1029', 'MCTG1017', 'MATG1078', 'MEDG1021', 'DIGG2033', 'TURG2033', 'DING2035', 'CADG2035', 'GEOG1028', 'AUDG2026', 'IDIG1010', 'LOGT3009', 'MATG1077', 'MEDG1015', 'MATG2008', 'MEDG2014', 'OCEG1040', 'GEOG1045', 'INDG1047', 'CADG2032', 'NAVG1025', 'ALIG1043', 'CIVG1043', 'BIOG1021', 'MCTG1012', 'ECOG2059', 'TELG1028', 'MTRG1032', 'PETG1028', 'SOFG1007', 'LOGT3005', 'ACUG1049', 'AGRG1027', 'LOGT3007', 'TICG1018', 'ECOG2068', 'MING1031', 'MECG1067', 'PETG1024', 'NAVG1028', 'INDG1051', 'MECG1058', 'ADSG1026', 'NAVG1032', 'ESTG1043', 'MATG1046', 'MATG1047', 'AGRG1024', 'CADG2034', 'DIGG2027', 'ELEG1043', 'CADG2030', 'ESTG1063', 'CCAG2023', 'QUIG1045', 'ESTG1057', 'CADG2038', 'ELET3003', 'IDIG1006', 'MING1038', 'GEOG1033', 'ALIG1033', 'OCEG1049', 'MATG1062', 'MTRG1025', 'TLMG1026', 'ESTG1033', 'OCEG1035', 'TURG2037', 'INDG1801', 'MATT3002', 'ARQG2021', 'MATG1072', 'ALIG1041', 'TURG2030', 'ARQG2031', 'MEDG1019', 'ECOG2057', 'TELG1027', 'CADG2029', 'PETG1030', 'CCPG1043', 'EYAT3001', 'INDG1060', 'DING2027', 'ECOG1009', 'PETG1025', 'ARQG2043', 'BIOG1023', 'MECG1053', 'ELEG1050', 'ARQG2042', 'DING2033', 'TELG1032', 'LOGT3002', 'NUTG2027', 'ACUG1041', 'ADSG1021', 'ARQG2034', 'NAVG1035', 'BIOG1025', 'ACUG1051', 'ALIG1037', 'NUTG2040', 'AGRG1025', 'DING2043', 'CADG2028', 'LOGG1022', 'INDG1061', 'EYAG1036', 'ELEG1038', 'CADG2037', 'DIGG2039', 'MATG1076', 'CIVG1040', 'NAVT3002', 'BIOG1028', 'CCPG1039', 'DIGG2040', 'DING2025', 'ARQG2037', 'CCPG1046', 'ARTG2032', 'CCAG1002', 'EYAG1037', 'MECG1041', 'MECG1050', 'DIGG2026', 'QUIG1037', 'MEDG2017', 'MEDG1017', 'CCPG1803', 'GEOG1050', 'INDG1037', 'GEOG1041', 'CADG2025', 'MATG2009', 'AUDG2033', 'CADG2027', 'ARQG2025', 'CIVG1046', 'ELEG1037', 'IDIG2012', 'MECT3002', 'ARTG2029', 'MTRG1036', 'PETG1027', 'OCEG1034', 'DIGG2029', 'MTRG1024', 'TLMG1032', 'TLMG1036', 'AUDG2039', 'MATG1068', 'CIVG1047', 'OCEG1051', 'CCPG1034', 'TELG1034', 'MATG1065', 'TELG1038', 'ACUG1055', 'INDG1048', 'OCEG1038', 'AGRG1028', 'ECOG2041', 'MING1023', 'MATG1060', 'ALIG1046', 'TELG1029', 'NAVG1041', 'ESTG1048', 'LOGG1018', 'ACUG1043', 'NUTG2042', 'ESTG1050', 'INDG1035', 'MECG1046', 'ESTG1052', 'MEDG2015', 'MEDG2019', 'AGRG1033', 'MING1034', 'OCEG1030', 'PETG1026', 'QUIG1042', 'QUIG1047', 'TLMG1033', 'OCET3002', 'ACUG1053', 'INDG1053', 'JURG2006', 'FISG1007', 'CIVG1036', 'IDIG1009', 'QUIG1039', 'TELG1039', 'CADG2036', 'ESTG1039', 'DING2037', 'DING2023', 'MTRG1038', 'DIGG2023', 'ECOG2069', 'MTRG1023', 'MCTG1015', 'NAVG1040', 'MATG1079', 'MATG1803', 'ACUG1048', 'SOFG1006', 'MECG1043', 'CCPG1051', 'AGRG1026', 'NUTG2029', 'MECT3005', 'OCEG1045', 'MATG1069', 'MEDG2016', 'AUDG2028', 'GEOG1027', 'MECG1051', 'MEDG2018', 'ECOG2061', 'TURG2019', 'DING2042', 'GEOG1044', 'MATG1058', 'ACUG1040', 'FISG1006', 'DING2041', 'ALIG1032', 'GEOG1035', 'TURG2022', 'MECG1055', 'ECOG2062', 'ADSG1024', 'ARQG2020', 'INDG1034', 'ESTG2004', 'MEDG1020', 'NAVG1038', 'ECOG2063', 'FISG1009', 'EYAG1045', 'MATG1053', 'ADSG1023', 'ESTT3002', 'TURG2024', 'TURG2031', 'ESTG1049', 'MCTG1013', 'PETG1023', 'QUIG1046', 'ESTG1054', 'MECG1059', 'TLMG1035', 'ARQG2028', 'ECOG2044', 'EYAG1042', 'MATG1051', 'MECG1065', 'MATG1048', 'ELET3001', 'MCTG1016', 'GEOG1030', 'NUTG2026', 'ARQG2029', 'GEOG1032', 'MECG1049', 'CADG2040', 'GEOG1038', 'DIGG2032', 'ELEG1047', 'QUIG1032', 'ARQG2038', 'ALIG1038', 'MTRG1028', 'NUTG2034', 'CCAG2022', 'MCTT3014', 'MATG1050', 'ELEG1032', 'MING1035', 'AGRG1038', 'DING2039', 'ELEG1049', 'ESTG1037', 'MTRG1029', 'OCEG1050', 'OCEG1036', 'ADSG1025', 'CIVG1056', 'MING1027', 'AUDG2044', 'LOGG1017', 'ALIG1031', 'GEOG1037', 'TELG1042', 'TLMG1027', 'ESTG1040', 'INDG1056', 'CADG2039', 'CIVG1059', 'CIVG1058', 'MATG1064', 'ACUG1057', 'ECOG2049', 'CCPG1044', 'ESTG1036', 'MCTG1014', 'FISG1005', 'NUTG2037', 'ESTG1041', 'EYAT3002', 'MATG1802', 'ARQG2026', 'QUIG1033', 'TLMG1037', 'TURG2020', 'MING1024', 'ELEG1041', 'DING2031', 'CCPG1049', 'OCEG1046', 'QUIG1040', 'MEDG1022', 'ADSG1019', 'OCEG1033', 'ECOG2066', 'QUIG1036', 'SOFG1009', 'IDIT3002', 'OCEG1047', 'CIVG1038', 'QUIG1041', 'LOGG1020', 'DIGG2030', 'TELG1035', 'ALIG1050', 'DIGG2031', 'MCTT3015', 'ACUG1047', 'TURG2023', 'JURG2004', 'ARTG2026', 'CCPG1059', 'ELEG1029', 'DING2026', 'NUTG2033', 'INDG1045', 'CIVG1050', 'ALIG1042', 'DING2040', 'MECT3004', 'TLMG1029', 'NAVG1039', 'ELEG1044', 'MATG1801', 'ACUG1035', 'MCTG1020', 'TURG2021', 'ESTG1034', 'NAVG1027', 'INDG1042', 'INDG1046', 'INDG1058', 'MTRG1026', 'MTRG1027', 'GEOG1048', 'ACUG1056', 'ELEG1040', 'CCPG1036', 'ALIG1030', 'TELG1040']

In [44]:
# join entre lista_error y list_encoder para obtener los elementos que están en lista_error y en list_encoder
lista_error_encoder = list(set(lista_error) & set(list_encoder))

In [45]:
len(lista_error_encoder)

85

In [46]:
lista_error_encoder

['LOGG1020',
 'MATG1069',
 'OCEG1039',
 'MING1024',
 'AGRG1022',
 'MING1040',
 'ARQG2022',
 'ARQG2043',
 'OCEG1040',
 'MATG1060',
 'EYAT3004',
 'ESTG1050',
 'MATG1077',
 'OCET3002',
 'LOGT3007',
 'EYAT3002',
 'MING1034',
 'LOGT3002',
 'MATG1067',
 'OCEG1047',
 'GEOG1051',
 'MATG1074',
 'ESTG1057',
 'MECT3003',
 'IDIT3004',
 'PETG1021',
 'NAVT3003',
 'GEOG1038',
 'LOGG1024',
 'MING1041',
 'TELG1038',
 'MATG1071',
 'ELET3002',
 'EYAT3003',
 'IDIT3003',
 'MING1033',
 'GEOG1035',
 'GEOG1040',
 'MING1025',
 'ESTG1055',
 'OCEG1038',
 'TLMG1026',
 'AGRG1030',
 'MCTT3015',
 'OCEG1035',
 'AGRG1040',
 'NAVT3002',
 'LOGT3010',
 'TLMG1025',
 'TELG1034',
 'NAVT3001',
 'LOGT3011',
 'LOGG1023',
 'AGRG1028',
 'OCEG1046',
 'GEOG1048',
 'ARQG2028',
 'LOGT3009',
 'LOGT3012',
 'GEOG1028',
 'OCEG1051',
 'NAVG1027',
 'ECOG1008',
 'ESTG1047',
 'OCEG1049',
 'MING1027',
 'GEOG1029',
 'OCEG1033',
 'MECT3002',
 'NAVG1025',
 'MING1029',
 'ARQG2036',
 'LOGT3006',
 'ESTG1049',
 'LOGT3013',
 'MCTT3011',
 'MCTT3014',
 'NAVG1031',
 'ARQG2030',
 'ADST3002',
 'CCPT3004',
 'ELET3001',
 'ESTG1048',
 'ESTT3002',
 'ARQG2023']

In [51]:
df_materias_xslx_faltantes_encoder = df_materias_xslx[df_materias_xslx["CodigoMateria"].isin(lista_error_encoder)].copy()
df_materias_xslx_faltantes_encoder[["CodigoMateria", "NombreMateria"]]

    CodigoMateria                                   NombreMateria
49       ADST3002                            CIENCIAS AMBIENTALES
50       AGRG1022                        AGRICULTURA DE PRECISIÓN
56       AGRG1028  GESTIÓN DE UNIDADES DE PRODUCCIÓN AGROPECUARIA
58       AGRG1030                           MECANIZACIÓN AGRÍCOLA
66       AGRG1040                          PRODUCCIÓN VEGETAL III
..            ...                                             ...
647      PETG1021                      INGENIERÍA DE PRODUCCIÓN I
687      TELG1034                PROCESAMIENTO DIGITAL DE SEÑALES
690      TELG1038                    SISTEMAS DE COMUNICACIONES I
697      TLMG1025          CALIDAD DE SERVICIO Y REDES MULTIMEDIA
698      TLMG1026               CIBERSEGURIDAD Y GESTIÓN DE REDES

[85 rows x 2 columns]

In [54]:
# in df_materias_xslx_faltantes and not in df_materias_xslx_faltantes_encoder
faltantes_no_encoder = set(df_materias_xslx_faltantes["CodigoMateria"]) - set(df_materias_xslx_faltantes_encoder["CodigoMateria"])
df_materias_xslx_faltantes_no_encoder = df_materias_xslx[df_materias_xslx["CodigoMateria"].isin(faltantes_no_encoder)].copy()
df_materias_xslx_faltantes_no_encoder[["CodigoMateria", "NombreMateria"]]

    CodigoMateria                                      NombreMateria
20       ACUG1058                 MATERIA INTEGRADORA DE ACUICULTURA
22       ADMG1005                        EMPRENDIMIENTO E INNOVACIÓN
23       ADMG1006  GESTIÓN DE PROYECTOS Y REGULACIÓN EN TELECOMUN...
24       ADMG1007                             ESTRATEGIAS DE GESTIÓN
25       ADMG2022                      ADMINISTRACIÓN DE OPERACIONES
..            ...                                                ...
675      QUIG1050          MATERIA INTEGRADORA DE INGENIERÍA QUÍMICA
686      TELG1033          MATERIA INTEGRADORA DE TELECOMUNICACIONES
695      TICG1801                           BASES DE DATOS AVANZADAS
703      TLMG1031                  MATERIA INTEGRADORA DE TELEMÁTICA
717      TURG2029                     MATERIA INTEGRADORA DE TURISMO

[62 rows x 2 columns]

In [49]:
df_2026_1S = pd.read_csv('../data\\riesgo_academico\\PAO_2026_1S.csv')

In [50]:
df_2026_1S["COD_MATERIA_ACAD_MO"].nunique()

640